# Generated by Django 5.0.7 on 2024-09-17 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="생성된 일시")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="수정된 일시")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="삭제된 일시")),
                ("username", models.CharField(max_length=255, unique=True, verbose_name="유저명")),
                ("is_active", models.BooleanField(default=True, verbose_name="계정 활성화 여부")),
                ("is_staff", models.BooleanField(default=False, verbose_name="관리자 권한 여부")),
                ("is_superuser", models.BooleanField(default=False, verbose_name="최고 관리자 권한 여부")),
            ],
            options={
                "verbose_name": "User",
                "verbose_name_plural": "Users",
                "db_table": "user",
            },
        ),
    ]
