# Generated by Django 5.0.7 on 2024-09-21 07:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="생성된 일시")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="삭제된 일시")),
                ("address_line", models.CharField(max_length=255, verbose_name="주소")),
                ("postal_code", models.CharField(max_length=20, verbose_name="우편번호")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_addresses",
                        to="user.user",
                        verbose_name="유저",
                    ),
                ),
            ],
            options={
                "verbose_name": "Address",
                "verbose_name_plural": "Addresses",
                "db_table": "addresses",
            },
        ),
    ]
